<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\activitylogpic.jpg" />
    <None Remove="images\background.jpeg" />
    <None Remove="images\background.jpg" />
    <None Remove="images\Cyber.jpg" />
    <None Remove="images\taskpic.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\activitylogpic.jpg" />
    <Resource Include="images\background.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Cyber.jpg" />
    <Resource Include="images\taskpic.jpg" />
  </ItemGroup>

</Project>
